sudo: required

services:
  - docker

script:
  - docker build -t directus .
  - docker-compose up -d
  - sleep 42
  - docker exec dockerdirectus_directus_1 /bin/sh -c "curl -f localhost:80"
  - docker logs dockerdirectus_directus_1
