# Central Volumes Image
volumes:
  image: tianon/true
  volumes:
    # Directus
    - "./logs/:/var/www/html/api/logs"
    - "./media/:/var/www/html/media"

    # DB
    - "./db/:/var/lib/mysql"

# Central NGINX-Proxy
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  restart: always

mysql:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=Un1c0rns_4r3_4w3s0m3
    - MYSQL_DATABASE=directus
    - MYSQL_USER=directus
    - MYSQL_PASSWORD=Un1c0rn!
  volumes_from:
    - "volumes"
  restart: always

directus:
  image: beevelop/directus
  environment:
    - VIRTUAL_HOST=directus.example.com
    - SITE_URL=http://directus.example.com
    - ADMIN_EMAIL=directus@example.com
    - SITE_NAME=Dockerectus
    - ADMIN_PASSWORD=Un1c0rn
    
    - SAMPLE_DATA=True
  links:
    - mysql:mysql
  volumes_from:
    - "volumes"
  restart: always
